language: node_js
node_js:
  - "9"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - npm install
  - npm run generate

script:
  - echo "Tests"
  - npm run test
  - ls

deploy:
  provider: pages
  keep_history: true
  skip_cleanup: true
  github_token: $GITHUB_ACCESS_TOKEN
  target_branch: gh-pages
  local_dir: dist
  on:
    branch: master